version: "3.9"  # optional since v1.27.0
services:
  python:
    platform: linux/arm
    build: .
    security_opt:
      - seccomp:unconfined
    volumes:
      - .:/code
    devices:
      - /dev/gpiomem:/dev/gpiomem
    tty: true
